server:
  port: 8084

spring:
  application:
    name: RATING-SERVICE
  config:
    import: optional:configserver:http://localhost:8087

  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: microservice


