server:
  port: 8083


spring:
  h2:
    console:
      settings:
        web-allow-others: true
      enabled: true
      path: /h2
  datasource:
    url:  jdbc:h2:~/microservice
    username: sa
    password:
    driver-class-name:  org.h2.Driver
  jpa:
    generate-ddl: true

    hibernate:
      ddl-auto: update
  application:
    name: HOTEL-SERVICE

eureka:
  instance:
    prefer-ip-address:  true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url.defaultZone:  http://localhost:8761/eureka